name: Publish to NPM (OIDC)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write 

    steps:
      # ----------------------------------------------------
      # Checkout
      # ----------------------------------------------------
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # ----------------------------------------------------
      # Setup Node.js (OIDC)
      # ----------------------------------------------------
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/

      # ----------------------------------------------------
      # Install dependencies
      # ----------------------------------------------------
      - run: npm ci

      # ----------------------------------------------------
      # Publish to NPM (Trusted Publishing)
      # ----------------------------------------------------
      - run: npm publish --access public --provenance